from __future__ import annotations

from enum import Enum

BASE_URL = "https://www.tbca.net.br/"
SEARCH_ENDPOINT = "base-dados/composicao_alimentos.php"

class FoodGroup(str, Enum):
    SUGARS_AND_SWEETS = "75"
    INDUSTRIALIZED_FOODS = "82"
    SPECIAL_PURPOSE_FOODS = "78"
    BEVERAGES = "72"
    MEAT_AND_DERIVATIVES = "70"
    CEREALS_AND_DERIVATIVES = "65"
    FAST_FOOD = "77"
    FRUITS_AND_DERIVATIVES = "67"
    FATS_AND_OILS = "68"
    LEGUMES_AND_DERIVATIVES = "84"
    MILK_AND_DERIVATIVES = "71"
    MISCELLANEOUS = "76"
    NUTS_AND_SEEDS = "85"
    EGGS_AND_DERIVATIVES = "74"
    FISH_AND_SEAFOOD = "69"
    COMPLETE_MEALS = "83"
    VEGETABLES_AND_DERIVATIVES = "66"


FOOD_GROUPS: dict[str, str] = {
    FoodGroup.SUGARS_AND_SWEETS.value: "AÇÚCARES E DOCES",
    FoodGroup.INDUSTRIALIZED_FOODS.value: "ALIMENTOS INDUSTRIALIZADOS",
    FoodGroup.SPECIAL_PURPOSE_FOODS.value: "ALIMENTOS PARA FINS ESPECIAIS",
    FoodGroup.BEVERAGES.value: "BEBIDAS",
    FoodGroup.MEAT_AND_DERIVATIVES.value: "CARNES E DERIVADOS",
    FoodGroup.CEREALS_AND_DERIVATIVES.value: "CEREAIS E DERIVADOS",
    FoodGroup.FAST_FOOD.value: "FAST FOOD",
    FoodGroup.FRUITS_AND_DERIVATIVES.value: "FRUTAS E DERIVADOS",
    FoodGroup.FATS_AND_OILS.value: "GORDURAS E ÓLEOS",
    FoodGroup.LEGUMES_AND_DERIVATIVES.value: "LEGUMINOSAS E DERIVADOS",
    FoodGroup.MILK_AND_DERIVATIVES.value: "LEITE E DERIVADOS",
    FoodGroup.MISCELLANEOUS.value: "MISCELÂNEAS",
    FoodGroup.NUTS_AND_SEEDS.value: "NOZES E SEMENTES",
    FoodGroup.EGGS_AND_DERIVATIVES.value: "OVOS E DERIVADOS",
    FoodGroup.FISH_AND_SEAFOOD.value: "PESCADOS E FRUTOS DO MAR",
    FoodGroup.COMPLETE_MEALS.value: "REFEIÇÕES COMPLETAS",
    FoodGroup.VEGETABLES_AND_DERIVATIVES.value: "VEGETAIS E DERIVADOS",
}


class FoodType(str, Enum):
    IN_NATURA = "65"
    PROCESSED_INGREDIENT = "66"
    PROCESSED_INGREDIENT_LACTOSE_FREE = "71"
    PROCESSED_READY_TO_EAT = "67"
    HOSPITAL_DIETS = "79"
    PREPARATION = "68"
    TEXTURE_MODIFIED_PREPARATION = "69"
    DIETETIC_VEGAN_VEGETARIAN_LACTOSE_FREE = "72"
    GLUTEN_FREE_PREPARATION = "73"
    GLUTEN_AND_LACTOSE_FREE_PREPARATION = "74"
    VEGAN_VEGETARIAN_PREPARATION = "75"
    VEGAN_VEGETARIAN_LACTOSE_FREE = "76"
    VEGAN_VEGETARIAN_LACTOSE_AND_GLUTEN_FREE = "77"
    DIETETIC_PREPARATION = "80"
    LIGHT_PREPARATION = "81"
    LACTOSE_FREE_PREPARATION = "78"
    SIMPLE_FOOD_PREPARATION = "70"


FOOD_TYPES: dict[str, str] = {
    FoodType.IN_NATURA.value: "ALIMENTO IN NATURA",
    FoodType.PROCESSED_INGREDIENT.value: (
        "ALIMENTO PROCESSADO (INGREDIENTE)"
    ),
    FoodType.PROCESSED_INGREDIENT_LACTOSE_FREE.value: (
        "ALIMENTO PROCESSADO (INGREDIENTE/SEM LACTOSE)"
    ),
    FoodType.PROCESSED_READY_TO_EAT.value: (
        "ALIMENTO PROCESSADO PRONTO PARA CONSUMO"
    ),
    FoodType.HOSPITAL_DIETS.value: "DIETAS HOSPITALARES",
    FoodType.PREPARATION.value: "PREPARAÇÃO",
    FoodType.TEXTURE_MODIFIED_PREPARATION.value: (
        "PREPARAÇÃO (ALIMENTO COM ALTERAÇÃO DE TEXTURA)"
    ),
    FoodType.DIETETIC_VEGAN_VEGETARIAN_LACTOSE_FREE.value: (
        "PREPARAÇÃO "
        "(ALIMENTO DIETÉTICO/VEGANO/VEGETARIANO/SEM LACTOSE)"
    ),
    FoodType.GLUTEN_FREE_PREPARATION.value: (
        "PREPARAÇÃO (ALIMENTO SEM GLÚTEN)"
    ),
    FoodType.GLUTEN_AND_LACTOSE_FREE_PREPARATION.value: (
        "PREPARAÇÃO (ALIMENTO SEM GLÚTEN/SEM LACTOSE)"
    ),
    FoodType.VEGAN_VEGETARIAN_PREPARATION.value: (
        "PREPARAÇÃO (ALIMENTO VEGANO/VEGETARIANO)"
    ),
    FoodType.VEGAN_VEGETARIAN_LACTOSE_FREE.value: (
        "PREPARAÇÃO "
        "(ALIMENTO VEGANO/VEGETARIANO/SEM LACTOSE)"
    ),
    FoodType.VEGAN_VEGETARIAN_LACTOSE_AND_GLUTEN_FREE.value: (
        "PREPARAÇÃO "
        "(ALIMENTO VEGANO/VEGETARIANO/SEM LACTOSE/SEM GLÚTEN)"
    ),
    FoodType.DIETETIC_PREPARATION.value: (
        "PREPARAÇÃO DIETÉTICA"
    ),
    FoodType.LIGHT_PREPARATION.value: "PREPARAÇÃO LIGHT",
    FoodType.LACTOSE_FREE_PREPARATION.value: (
        "PREPARAÇÕES SEM LACTOSE"
    ),
    FoodType.SIMPLE_FOOD_PREPARATION.value: (
        "PREPARO SIMPLES DO ALIMENTO"
    ),
}